package models

import (
	"github.com/Deeksharma/taskmanager/internal/enum"
	"go.mongodb.org/mongo-driver/v2/bson"
	"time"
)

var TaskCollection = "task" // _id is autogenerated

type Task struct {
	ID          bson.ObjectID   `json:"_id" bson:"_id"`
	TaskID      string          `json:"task_id" bson:"task_id"`
	Title       string          `json:"title" bson:"title"`
	Description string          `json:"description" bson:"description"`
	Owner       string          `json:"owner" bson:"owner"`
	Status      enum.TaskStatus `json:"status" bson:"status"`
	CreatedAt   time.Time       `json:"created_at" bson:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at" bson:"updated_at"`
}

type CreateTaskRequestBody struct {
	Title       string `json:"title" bson:"title" validate:"required"`
	Description string `json:"description" bson:"description" validate:"required"`
}

type UpdateTaskRequestBody struct {
	Title       string          `json:"title" bson:"title"`
	Description string          `json:"description" bson:"description"`
	Owner       string          `json:"owner" bson:"owner"`
	Status      enum.TaskStatus `json:"status" bson:"status" validate:"eq=Created|eq=InProgress|eq=Succeeded|eq=Deleted"`
}

var SortingColumns = []string{"title", "owner", "created_at", "updated_at"}
var FilteringColumns = []string{"owner", "status"}
